config/routes.rb
Rails.application.routes.draw do

  resources :tutor_statements

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # STUDENTS
  authenticated :user, ->(u) { u.type == :student } do
    root 'accounts#student_dashboard', as: 'student_root'
    resources :students, only: [:update]
    resources :tutors, only: [:index, :show]
    resources :purchases, only: [:new, :create]
    get 'complete_registration', to: 'students#complete_registration'
  end

  # TUTORS
  authenticated :user, ->(u) { u.type == :tutor } do
    root 'accounts#tutor_dashboard', as: 'tutor_root'
    resources :tutors, only: [:show, :update]
    resources :lessons do
      resources :time_slots, only: [:index, :create, :destroy]
    end
    get 'complete_registration', to: 'tutors#complete_registration'
    get 'subcategory', to: 'lessons#sub_category'
  end

  # USERS
  authenticated :user do
    resources :conversations, only: [:index, :show, :new, :create, :send] do
      member do
        post :reply
        post :trash
        post :untrash
      end
    end
    resources :statements, only: :show, controller: 'teacher_statements', as: 'teacher_statements' do
      get :show, defaults: {format: 'pdf'}, on: :member
    end
  end

  # VISITORS
  unauthenticated :user do
    resources :students, only: [:new, :create]
    resources :tutors, only: [:new, :create]

  end

  # EVERYONE
  resources :lessons, only: [:show]
  resources :reservations, only: [:create, :index, :show, :update] do
    get :available, on: :collection
    get :days, on: :collection
    get :confirm, on: :member
  end

  get 'search' => 'lessons#index'
  resources :pages, except: :show
  get ':id', to: 'pages#show', as: :static_page
  root 'welcome#index'
end

app/models/tutor_statement.rb
# /app/models/tutor_statement.rb
class TutorStatement < ActiveRecord::Base
  belongs_to :tutor

  STATEMENT_TIME_ZONE = 'Eastern Time (US & Canada)'
  COMMISSIONS = [30, 25, 20, 10, 0]

  validates_uniqueness_of :tutor_id, scope: [:year, :month, :week]

  scope :previous_week, -> { where(week: Time.now.prev_week.wday, month: Time.now.prev_week.month, year: Time.now.prev_week.year) }
  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where('published IS NULL OR published = ?', false).where(finalized: true) }
  scope :unfinalized, -> { where('finalized IS NULL OR finalized = ?', false) }
  scope :ordered, -> { order('year, month') }

  def self.past
    now = Time.find_zone(STATEMENT_TIME_ZONE).now
    where('(month + year * 12) < ?', now.month + now.year * 12)
  end

  def self.from_tutor(tutor, attributes = {})
    now = Time.find_zone(STATEMENT_TIME_ZONE).now
    defaults = { year: now.year, month: now.month }
    attributes.slice!(:year, :month)
    result = where(tutor_id: tutor).where(defaults.merge(attributes)).first_or_create
    result
  end

  def self.generate_all_for_current_month
    time = Time.find_zone(STATEMENT_TIME_ZONE).now
    generate_for_year_and_month(time.year, time.month)
  end

  def self.generate_all_for_previous_month
    time = Time.find_zone(STATEMENT_TIME_ZONE).now.prev_month
    generate_for_year_and_month(time.year, time.month)
  end

  def self.generate_all_for_previous_week
    # time = Time.find_zone(STATEMENT_TIME_ZONE).now.prev_week
    generate_for_year_and_month_and_week
  end

  def self.generate_for_year_and_month_and_week
    time = Time.find_zone(STATEMENT_TIME_ZONE).now.prev_week
    date_range = (time..time.end_of_week)
    reservations = Reservation.unscoped.select('DISTINCT(reservations.tutor_id), *')
                   .with_states(:completed, :reserved).where(starts_at: date_range)
                   .where(reservation_type: [:paid, :comped, :package])
    tutors = reservations.map(&:tutor)

    tutors.each {|tutor|
      TutorStatement.where(tutor_id: tutor.id, week: week, month: month, year: year).first_or_create
    }
  end

  def finalize
    return false if finalized? || !date_range.last.past?
    # self.pdf = tutorStatementPdf.new(self).pdferize
    self.finalized = true
    save
  end

  def publish
    finalized? and update_column(:published, true)
  end

  def month_name
    Date::MONTHNAMES[month]
  end

  def commission
    self[:commission] or 25
  end

  def finalized?
    changed? ? !!TutorStatement.find(self).try(:finalized) : !!self[:finalized]
  end

  def save
    !finalized? and super
  end

  def reservations
    tutor.reservations.where(starts_at: date_range).with_states(:completed, :reserved).ascending_order
  end

  def reservations_gross_payable
    reservations.where(reservation_type: [:comped, :paid, :package]).inject(0.0) do |accumulator, reservation|
      accumulator + reservation.gross_payable_value
    end
  end

  def miscellaneous_payable
    tutor_statement_miscellaneous_line_items.inject(0.0) do |acc, item|
      acc + item.amount
    end
  end

  def reservations_net_payable
    reservations_gross_payable - commission_value
  end

  def commission_value
    reservations_gross_payable * (commission / 100.0)
  end

  def total_payable
    reservations_net_payable + miscellaneous_payable
  end

  def date_range
    time = Time.find_zone(STATEMENT_TIME_ZONE).now.prev_week
    (time..time.end_of_week)
  end
end

app/controllers/tutor_statements_controller.rb
# /app/controllers/tutor_statements_controller.rb
class TutorStatementsController < ApplicationController
  before_action :load_tutor

  def show
    statement = @tutor.statements.published.find_by_id(params[:id])
    if statement
      statement
    else
      not_found
    end
  end

  private

  def load_tutor
    @tutor = current_user.tutor
  end
end

app/views/tutor_statements/_form.html.erb
<%= form_for(@tutor_statement) do |f| %>
  <% if @tutor_statement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutor_statement.errors.count, "error") %> prohibited this tutor_statement from being saved:</h2>

      <ul>
      <% @tutor_statement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tutor_statements/edit.html.erb
<h1>Editing tutor_statement</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutor_statement %> |
<%= link_to 'Back', tutor_statements_path %>

app/views/tutor_statements/index.html.erb
<h1>Listing tutor_statements</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutor_statements.each do |tutor_statement| %>
      <tr>
        <td><%= link_to 'Show', tutor_statement %></td>
        <td><%= link_to 'Edit', edit_tutor_statement_path(tutor_statement) %></td>
        <td><%= link_to 'Destroy', tutor_statement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutor statement', new_tutor_statement_path %>

app/views/tutor_statements/new.html.erb
<h1>New tutor_statement</h1>

<%= render 'form' %>

<%= link_to 'Back', tutor_statements_path %>

app/views/tutor_statements/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tutor_statement_path(@tutor_statement) %> |
<%= link_to 'Back', tutor_statements_path %>