config/routes.rb
Rails.application.routes.draw do

  resources :tutor_statements

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # STUDENTS
  authenticated :user, ->(u) { u.type == :student } do
    root 'accounts#student_dashboard', as: 'student_root'
    resources :students, only: [:update]
    resources :tutors, only: [:index, :show]
    resources :purchases, only: [:new, :create]
    get 'complete_registration', to: 'students#complete_registration'
  end

  # TUTORS
  authenticated :user, ->(u) { u.type == :tutor } do
    root 'accounts#tutor_dashboard', as: 'tutor_root'
    resources :tutors, only: [:show, :update]
    resources :lessons do
      resources :time_slots, only: [:index, :create, :destroy]
    end
    get 'complete_registration', to: 'tutors#complete_registration'
    get 'subcategory', to: 'lessons#sub_category'
  end

  # USERS
  authenticated :user do
    resources :conversations, only: [:index, :show, :new, :create, :send] do
      member do
        post :reply
        post :trash
        post :untrash
      end
    end
    resources :statements, only: :show, controller: 'teacher_statements', as: 'teacher_statements' do
      get :show, defaults: {format: 'pdf'}, on: :member
    end
  end

  # VISITORS
  unauthenticated :user do
    resources :students, only: [:new, :create]
    resources :tutors, only: [:new, :create]

  end

  # EVERYONE
  resources :lessons, only: [:show]
  resources :reservations, only: [:create, :index, :show, :update] do
    get :available, on: :collection
    get :days, on: :collection
    get :confirm, on: :member
  end

  get 'search' => 'lessons#index'
  resources :pages, except: :show
  get ':id', to: 'pages#show', as: :static_page
  root 'welcome#index'
end

app/models/lesson.rb
# /app/models/lesson.rb
class Lesson < ActiveRecord::Base
  extend FriendlyId
  searchkick
  acts_as_commentable
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  LOCATION_ATTRIBUTES = [:latitude, :longitude]

  COMPLETE_ATTRIBUTES = [:name, :description, :address,
                         :phone_number, :amount,
                         :allowed_people, :green_zone,
                         :weeks_visible
                        ]
  validates *COMPLETE_ATTRIBUTES, presence: true

  validates :amount, :allowed_people, numericality: true
  validates :amount, :allowed_people, numericality: {greater_than: 0}

  enum level: [:beginner, :intermediate, :advanced]
  friendly_id :name, use: :slugged
  has_many :time_slots, dependent: :destroy
  has_many :reservations
  belongs_to :tutor, inverse_of: :lessons
  belongs_to :category
  delegate :time_zone, to: :tutor

  class << self
    def past_classes
      where('id < ?', 1000) # Fix me use reservations
    end

    def active_classes
      where('id < ?', 1000) # Fix me use reservations
    end

    # def search(search)
    #   wildcard_search = "%#{search}%"
    #   where('address LIKE :search OR description LIKE :search OR name LIKE :search', search: wildcard_search)
    # end
  end

  def class_name
    self.class.to_s.underscore
  end
end

app/controllers/lessons_controller.rb
# /app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @lessons = []
      @lessons = Lesson.search params[:search], page: params[:page], per_page: 20
      lessons_based_location = Lesson.near(params[:search])
      if  lessons_based_location.length > 0
        lessons_based_location.each do |lesson|
          @lessons << lesson
        end
      end
    else
      @lessons = Lesson.order(:address).page params[:page]
    end
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = current_user.tutor.lessons.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_time_slots_path(@lesson), notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end

  def sub_category
    @subcategory = Category.where(parent_id: params[:parent_id])
    render partial: 'subcategory', layout: false, locals: { subcategory: @subcategory }
  end

  private

  def set_lesson
    @lesson = Lesson.friendly.find(params[:id])
  end

  def lesson_params
    attrs = []
    attrs.push(:category_id)
    attrs.push(*Lesson::COMPLETE_ATTRIBUTES)
    params.require(:lesson).permit(attrs)
  end
end

app/views/lessons/_form.html.slim
.row
  .form-actions
    = form_for(@lesson) do |f|
      = render 'shared/errors', object: f.object
      .form-group
        = f.label :name
        = f.text_field :name
      .field-group
        = f.label :description
        = f.text_area :description
      .field-group
        = f.label :phone_number
        = f.number_field :phone_number
      .field-group
        = f.label :address
        = f.text_field :address, id: 'gmaps-input-address', placeholder: 'enter address'
      .field-group
        = f.label :amount
        = f.number_field :amount
      .field-group
        = f.label :allowed_people
        = f.number_field :allowed_people
      .field-group
        = f.label :category
        = select("lessons", "category", category_list.collect {|p| [ p.category_name, p.id ] }, {include_blank: 'None'})
      #subcategory
      .content-box.last-one
        = f.submit 'Save', class: 'btn btn-success'
    = link_to 'Manage Time Slots', lesson_time_slots_path(@lesson) if @lesson.persisted?
- content_for :javascript do
  javascript:
    jQuery(function() {
      var completer;
      completer = new GmapsCompleter({
      inputField: '#gmaps-input-address',
      errorField: '#gmaps-error',
      debugOn: false
      });
      completer.autoCompleteInit({
        country: 'us'
      });
    });

app/views/lessons/_subcategory.html.slim
= select("lesson", "category_id", @subcategory.collect {|p| [ p.category_name, p.id ] }, {include_blank: 'None'})

app/views/lessons/edit.html.slim
h1
  | Editing lesson
= render 'form'
= link_to 'Show', @lesson
|  | 
= link_to 'Back', lessons_path

app/views/lessons/index.html.slim
.row-fluid
  .span6
    h1 Major Category
    | 300 classes near me
  .span6
    .row-fluid
      .span4
        .minor_cateogry
          br
          a href=""  Minor Category
          br
          a href=""  Minor Category
          br
          a href=""  Minor Category

      .span4
        .minor_cateogry
          br
          a href=""  Minor Category
          br
          a href=""  Minor Category
          br
          a href=""  Minor Category
      .minor_cateogry
        br
        a href=""  Minor Category
        br
        a href=""  Minor Category
br
br
.row-fluid
  form action=""
    .span2
      .btn-group
        a.btn.btn-default href=""  class View
        a.btn.btn-primary href=""  Map View
    .span3
      input.search-query.search_page_4 placeholder=("Other City or Zip") type="text"
        span.glyphicon.glyphicon-search
    .span3
      | please put Map
    .span2
      select.select_time
        option value="time"  Time of Day
        option value="..."  ...
        option value="..."  ...
        option value="..."  ...
    .span1
      select.select_time
        option value="..."  Sort by
        option value="..."  ...
        option value="..."  ...
        option value="..."  ...
- @lessons.each do |lesson|
  - if lesson.present?
    hr
      .row-fluid
        .span3
          =image_tag("env.png")
        .span6
          b
            = link_to lesson.name, lesson_path(lesson)
          br
          b
            | with
            / =lesson.tutor.name
            | , Neighborhood(2.7 mi)
          br
          p
            = lesson.description
        .span2
          b
            = number_to_currency(lesson.amount, unit: '₹')
          br
          | 7:00 - 8:00 am
          br
          a hef=""  +12 more
        .span1
          .box_page4 style="padding: 10px 0 0 10px;border-radius: 10px;margin-left:1px; height:100px;bord- style: solid;width: 100px;"
            br
            | Book Now
            br
            =lesson.allowed_people
            | spots left

app/views/lessons/new.html.slim
ul.breadcrumb
  li
    a href="/"  Home
    span.divider /
  li.active New Class

h1
  | New lesson
= render 'form'
= link_to 'Back', lessons_path

app/views/lessons/show.html.slim
ul.breadcrumb
  li
    a href="/"  Home
    span.divider /
  li.active Class
.row-fluid
  .span8
    font size="10" = @lesson.name
    | &nbsp&nbsp&nbsp&nbsp&nbsp
    b
      | with
      = @lesson.tutor.name
    br
      br
        b
          = @lesson.address
          br
            / = @lesson.start_date
            br
              | 7:00 - 8:00 am
            a href=""  +12
  .span2
    b = number_to_currency(@lesson.amount)
    br
      | 7:00 - 8:00 am
      br
        | Wed,Oct 7
        br
          b
            a href=""  +12
  .span2
    .box style="padding: 10px 0 0 10px;border-radius: 10px;margin-left:1px; height:75px;border-style: solid;width: 100px;"
      = link_to 'Book Class Now', new_purchase_path(lesson: @lesson)
      br
        | 4 spots left
      = link_to 'Ask a question', new_conversation_path(lesson: @lesson)

br
.row-fluid
  .span10
    ul.nav.nav-pills
      li.active style="margin-left: -50%;"
        a.brand href="index.html"  Class Description
      li
        a.brand href="index.html" style="margin-left:1px;"  Instructor
      li
        a.brand href="index.html" style="margin-left:1px;"  Reviews
      li
        a.brand href="index.html" style="margin-left:1px;"  Map
      li
        a.brand href="index.html" style="margin-left:1px;"  Pictures
    br
      b Class Description :
      br
        p
          = @lesson.description
        b
          | Level: All
          br
          | Ages: All
          br
          | Avg Class Size : 10
          br
          | Attire: Comfortable
  .span2
    .box1 style="margin-top:50%;"
      b
        |Spread the Word
      br
      button.btn.btn-primary.btn-lg.btn-block type="button"  Invite a Friend
      br
      button.btn.btn-default type="button"  Like
      br
      br
      button.btn.btn-primary type="button"  Twitter

.row-fluid
  .span10
    .ins_profile
      b Instructor Profile :
      .row-fluid
        .span2
          br
          =image_tag("env.png")

        .span10
          | HTML is written in the form of HTML elements consisting of tags enclosed
          br
            | in angle brackets (like). HTML tags most commonly come in pairs like  and
            br
              | , although some tags represent empty elements and so are unpaired, for
              br
                | example. The first tag in a pair is the start tag, and the second tag is the end tag
                br
                  | (they are also called opening tags and closing tags).
                  br
                    | The purpose of a web browser is to read HTML documents and compose them into visible
                    br
  .span2
    h1
      | GOOGLE MAP
.row-fluid
  .span10
    .ins_profile
      b 94 % Positive Reviews (137 Reviews ) :
      .row-fluid
        .span2
          br
          br
            .clip_img
              =image_tag("thums_up.jpg")

        .span10
          | HTML is written in the form of HTML elements consisting of tags enclosed
          br
            | in angle brackets (like). HTML tags most commonly come in pairs like  and
            br
              | , although some tags represent empty elements and so are unpaired, for
              br
                | example. The first tag in a pair is the start tag, and the second tag is the end tag
                br
                  | (they are also called opening tags and closing tags).
                  br
                    | The purpose of a web browser is to read HTML documents and compose them into visible
                    br
                      br
                        | John Smith


      .row-fluid
        .span2
          br
          .clip_img
            =image_tag("thums_up.jpg")
        .span10
          | HTML is written in the form of HTML elements consisting of tags enclosed
          br
            | in angle brackets (like). HTML tags most commonly come in pairs like  and
            br
              | , although some tags represent empty elements and so are unpaired, for
              br
                | example. The first tag in a pair is the start tag, and the second tag is the end tag
                br
                  | (they are also called opening tags and closing tags).
                  br
                    | The purpose of a web browser is to read HTML documents and compose them into visible
                    br
                      br
                        | John Smith


      .row-fluid
        .span2
          br
          .clip_img
            =image_tag("thums_up.jpg")
        .span10
          | HTML is written in the form of HTML elements consisting of tags enclosed
          br
            | in angle brackets (like). HTML tags most commonly come in pairs like  and
            br
              | , although some tags represent empty elements and so are unpaired, for
              br
                | example. The first tag in a pair is the start tag, and the second tag is the end tag
                br
                  | (they are also called opening tags and closing tags).
                  br
                    | The purpose of a web browser is to read HTML documents and compose them into visible
                    br
                      br
                        | John Smith
      .four.columns(style="margin-top: 12px;")
        - if @lesson.time_slots_count > 0
          h2.sidebar Book a Lesson
          p.sidebar Click 'Book Now' to reserve a date and time for your lesson.
          p(style='font-size:11px') Times displayed in #{Time.zone.name}
          = render 'reservations/selector'