config/routes.rb
Rails.application.routes.draw do

  resources :tutor_statements

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # STUDENTS
  authenticated :user, ->(u) { u.type == :student } do
    root 'accounts#student_dashboard', as: 'student_root'
    resources :students, only: [:update]
    resources :tutors, only: [:index, :show]
    resources :purchases, only: [:new, :create]
    get 'complete_registration', to: 'students#complete_registration'
  end

  # TUTORS
  authenticated :user, ->(u) { u.type == :tutor } do
    root 'accounts#tutor_dashboard', as: 'tutor_root'
    resources :tutors, only: [:show, :update]
    resources :lessons do
      resources :time_slots, only: [:index, :create, :destroy]
    end
    get 'complete_registration', to: 'tutors#complete_registration'
    get 'subcategory', to: 'lessons#sub_category'
  end

  # USERS
  authenticated :user do
    resources :conversations, only: [:index, :show, :new, :create, :send] do
      member do
        post :reply
        post :trash
        post :untrash
      end
    end
    resources :statements, only: :show, controller: 'teacher_statements', as: 'teacher_statements' do
      get :show, defaults: {format: 'pdf'}, on: :member
    end
  end

  # VISITORS
  unauthenticated :user do
    resources :students, only: [:new, :create]
    resources :tutors, only: [:new, :create]

  end

  # EVERYONE
  resources :lessons, only: [:show]
  resources :reservations, only: [:create, :index, :show, :update] do
    get :available, on: :collection
    get :days, on: :collection
    get :confirm, on: :member
  end

  get 'search' => 'lessons#index'
  resources :pages, except: :show
  get ':id', to: 'pages#show', as: :static_page
  root 'welcome#index'
end

app/controllers/accounts_controller.rb
# /app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!

  def tutor_dashboard
    @past_lessons   = current_user.tutor.lessons.past_classes
    @active_classes = current_user.tutor.lessons.active_classes
  end
end

app/views/accounts/student_dashboard.html.slim
.dashboard-student
  .avatar-header.dashboard-header
    h3= t('greeting', name: current_user.name)
    p.last-one#online-tutors-count
      strong= t('.find_tutors')
  = link_to 'My Conversations', :conversations
  br
  = link_to 'My Reservations', :reservations
  .content-box-mega.last-one
    .row-fluid
      .span5

      .span6.offset1
        .row-fluid
          .span6
            .content-box-mega.first-one
              h3.first-one= t('.account_balance')
          .span6
            .content-box-mega.first-one
              h3.first-one= t('.session_history')
        h3.first-one= t('.favorite_tutors')
          p.manage-favorites= t('accounts.student_dashboard.no_favorite_tutors_online')

app/views/accounts/tutor_dashboard.html.slim
.row-fluid
  .span10
    h3
      |Trainer Dashboard
  .span2
    .content-box-mega.last-one
      .sidebar-box
        a href="/complete_registration"
          = t('.profile_update')
    = link_to 'My Conversations', :conversations
br
.row-fluid
  .span10
    ul.nav.nav-pills
      li.active
        a.brand href="#"  Active Class
      li
        a.brand href="#" style="margin-left:1px;"  Schedule
      li
        a.brand href="#" style="margin-left:1px;"  Class History
      li
        a.brand href="#" style="margin-left:1px;"  Inbox
      li
        a.brand href="#" style="margin-left:1px;"  Reviews
      li
        a.brand href="#" style="margin-left:1px;"  Performance
      li
        a.brand href="#" style="margin-left:1px;"  Finances
      li
        a.brand href="#" style="margin-left:1px;"  Setting
  .span2
    ul.nav.pull-right
      li
        button.btn.btn-primary.btn-lg style="margin-left:15px;" type="button"
          = link_to 'Create a New Class', new_lesson_path

table cellpadding="10" width="100%"
  tr
    td
      h4 Active Classes
    td
      h4 Date
    td
      h4 time
    td
      h4 Location
    td
      h4 Advertise
    td
      h4 Promo Codes
    td
      h4 Edit
  - @active_classes.each do |active_class|
    tr
      td
        .class_name style="margin-left: 30px;"
          b = link_to active_class.name, lesson_path(active_class)
      td
        / = active_class.start_date
        |  -
        / = active_class.end_date
      td
        | show times
      td
        = active_class.address
        br
          a href=""  (see on Map)
      td
        a href=""  Social Media
        br
          a href=""  Email
          br
            a href=""  Flyer
      td
        a href=""  create discount code
        br
          a href=""  create Referral code
      td
        = link_to 'Edit', edit_lesson_path(active_class)

br
  br
    table cellpadding="10" width="100%"
      tr
        td
          h4 Past Classes
        td
          h4 Date
        td
          h4 time
        td
          h4 Location
        td
          h4 Reviews
        td
          h4 Students
        td
          h4 Sales
      - @past_lessons.each do |past_class|
        tr
          td
            .class_name style="margin-left: 30px;"
              b = link_to past_class.name, lesson_path(past_class)
          td
            / = past_class.start_date
            |  -
            / = past_class.end_date
          td
            | show times
          td
            = past_class.address
            br
              a href=""  (see on Map)
          td
            a href=""  Social Media
            br
              a href=""  Email
              br
                a href=""  Flyer
          td
            a href=""  create discount code
            br
              a href=""  create Referral code
          td
            a href=""  Sales Page